### ISSUE TITLE
RFC: Jinja re-expansion in spec

### ISSUE THREAD

**Issue by praiskup** [devexp-db/distgen#43]
It would be nice if we could re-expand jinja statements in spec dictionary yaml, before we start to instantiate templates.  This is important from two reasons:
- specs are very small, compared to final templates
- if distgen was about to be made a library (my long term wish), it would be nice to be able to first calculate spec/macros/config and then very quickly use this variables for dozens of templates (`generate` method)

**Comment by bkabrda** [comment]
Yeah, I think we could do it this way:

* Load all the specs, including multispec, as we do it now.
* Serialize the resulting dict to in-memory string containing a yaml.
* Run recursive rendering on this in-memory yaml.
* Simply load the yaml back and use it as the resulting spec (unless we exceed max-passes).

Does that sound ok?

**Comment by praiskup** [comment]
I really dislike the recursive rendering using the jinja2 lib -> that's not what the language/library was designed for, and it is basically useless anyway *iff* anybody implemented your point 2.

I also really dislike removing minimizing the difference between spec/template.

**Comment by praiskup** [comment]
Or maybe I just don't understand your point #2 -- to me it seems to be much natural to allow recursive "rendering" (or calculating fixed-point) of spec, but not doing the recursive re-rendering of template yaml.  
Saying that, re-calculating the spec equivalent proposal to re-calculating of the whole template, but much natural to me.

**Comment by bkabrda** [comment]
I'm not sure we understand each other.

What I proposed in the comment above *is* about "recursive rendering" of spec, and it proposes a specific way how we could achieve that: In order to be able to use jinja2 syntax in spec values (which I think is desirable), it achieves recursive rendering by first "combining all specs into one" and then applying recursive rendering to this one spec. The way it achieves recursive rendering of the combined spec is by serializing it into a string, applying current recursive rendering strategy to it and then loading it back again. Does that make it clearer?

Alternatively, we *could* traverse all the (potentially nested) values inside the combined spec and re-render them individually, while checking that at least one of them has changed in every iteration. This solution has some different properties:

Let's call my original proposal solution 1 and the solution which traverses all the individual values (above) solution 2. Example spec:

```
foo: bar: baz
spam: {{ foo }}
```

* with solution 1, you'd get (after final deserialization in Python): `{'spam': {'bar': 'baz'}, 'foo': ...}` (`spam` is a dict now)
* with solution 2, you'd get (after final deserialization in Python): `{'spam': "'bar': 'baz'", 'foo': ...}` (`spam` is a string now)

I like option 1 more, so that's why I proposed the original solution.

**Comment by praiskup** [comment]
> Does that make it clearer?

Yes, but I still dislike the recursive jinja re-rendering of the final template (so anybody could, using the API in future, go through N templates, and apply **and only one** precalculated spec to all of them).  More, this way you can use the "streaming" fature of jinja2.

> Alternatively, we could traverse all the (potentially nested) values inside the combined spec and re-render them individually, while checking that at least one of them has changed.

This sounds much better, also I guess you can re-expand "recursively" -- by expanding particular node in yaml taking into account the spec state).  I don't think serialization is needed at all.  Yes, I admit that serialization is the easiest way how to implement this for the same result..

**Comment by praiskup** [comment]
> by expanding particular node in yaml taking into account the spec state

Sorry, I'm speaking about yaml, but I should rather speak about Python's dictionary at this point.

**Comment by TomasTomecek** [comment]
I might have a good use case for you: I prefer talking about it in person b/c it's pretty complicated.

**Comment by praiskup** [comment]
+1
